name: build test
on:
  workflow_call:
    inputs:
      DOCKERFILE_PATH:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

      # Authenticate to Google CLoud
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      # if: github.event_name != 'pull_request'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_CICD }}
        service_account: ${{ secrets.SA_EMAIL_CICD }}
        token_format: "access_token"

    # Docker login to GCP
    - name: Docker login to GCP
      uses: docker/login-action@v2
      # if: github.event_name != 'pull_request'
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    # Set SHORT SHA
    - run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - env:
        PUSH: ${{ github.event_name != 'pull_request'}}
      run: |
        echo $PUSH

    # Build setup
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # ON PR Build and Test
    # - name: Build and test
    #   uses: docker/build-push-action@v3
    #   if: github.event_name == 'pull_request'
    #   with:
    #     context: .
    #     push: false
    #     file: ${{ inputs.DOCKERFILE_PATH }}
    #     build-args: |
    #       NUGETPASSWORD=${{ secrets.NUGET_PASSWORD }}
    #       GHNUGETPASSWORD=${{ secrets.GH_NUGET_PASSWORD }}

    # Build & Push Docker Container Image to Google Artifact Registry
    - name: Build and push
      uses: docker/build-push-action@v3
      # if: github.event_name != 'pull_request'
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}/${{ inputs.APP_NAME }}
      with:
        context: .
        # push: true
        push: ${{ github.event_name != 'pull_request'}}
        file: ${{ inputs.DOCKERFILE_PATH }}
        build-args: |
          NUGETPASSWORD=${{ secrets.NUGET_PASSWORD }}
          GHNUGETPASSWORD=${{ secrets.GH_NUGET_PASSWORD }}
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ env.SHORT_SHA }},
          ${{ env.DOCKER_IMAGE }}:latest

  prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3