name: build test
on:
  workflow_call:
    secrets:
      SA_EMAIL_CICD:
        required: true

    # inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

      # Authenticate to Google CLoud
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      # if: github.event_name != 'pull_request'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_CICD }}
        service_account: ${{ secrets.SA_EMAIL_CICD }}
        token_format: "access_token"

