name: 'notify build failed'

on:
  workflow_call:
    inputs:
      WORKFLOW_NAME:
        required: false
        type: string
    secrets:
      SLACK_BUILD_UPDATE:
        required: true

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "color": "dc3545",
                  "fields": [
                    {
                      "title": "Build failed for ${{ github.repository }}",
                      "short": false,
                      "value": "Status: Failed"
                    },
                    {
                      "value": "<https://www.github.com/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_FILE }}|link>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BUILD_UPDATE}}
          WORKFLOW_FILE: ${{ inputs.WORKFLOW_NAME }}.yaml