name: "notify build start"

on:
  workflow_call:
    secrets:
      SLACK_BUILD_UPDATE:
        required: true

jobs:
  notify:
    # name: Sucess
    runs-on: ubuntu-latest
    steps:
      - id: slack
        name: Notify build start
        uses: slackapi/slack-github-action@v1.23.0
        with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
          channel-id: "C04BFN79UMS"
          payload: |
            {
              "text": "Build started for *${{ github.repository }}*<https://www.github.com/${{ github.repository }}/actions|[link]>\n",
              "attachments": [
                {
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BUILD_UPDATE}}