name: 'notify build failed'

on:
  workflow_call:
    inputs:
      update-ts:
        type: string
        required: false
    secrets:
      SLACK_BUILD_UPDATE:
        required: true

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          update-ts: ${{ inputs.update-ts}}
          payload: |
            {
              "attachments": [
                {
                  "color": "dc3545",
                  "fields": [
                    {
                      "title": "${{ github.repository }}/${{ github.workflow }}",
                      "short": false,
                      "value": "Status: Failed"
                    },
                    {
                      "value": "Ref: ${{ github.ref }}"
                    },

                    {
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BUILD_UPDATE}}
