name: 'notify build failed'

on:
  workflow_call:
    secrets:
      SLACK_BUILD_UPDATE:
        required: true

# "text": "Build succeeded for *${{ github.repository }}*\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Build succeeded for ${{ github.repository }}",
                      "short": false,
                      "value": "Status: Completed"
                    },
                    {
                      "value": "https://www.github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BUILD_UPDATE}}